# Travis

# sudo: required

language: objective-c

# addons:
#   hosts:
#     - mobileOrgWebDav.schnuddelhuddel.de

# dist: trusty

# services:
#   - docker
  
# before_install:
# - docker pull phylor/webdav-ssl
# - docker run -v $PWD/htpasswd:/htpasswd -v $PWD/certs:/certs -v $PWD/content:/var/www -h mobileOrgWebDav.schnuddelhuddel.de -p 32773:443 phylor/webdav-ssl

osx_image: xcode8.3

# xcode_project: MobileOrg.xcodeproj
# xcode_scheme: MobileOrg

script:
  xcodebuild test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO  -workspace MobileOrg.xcworkspace -scheme MobileOrg -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'|xcpretty

notifications:
  irc: 
    "irc.freenode.net#mobileorg"

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/adf14670ff7dc3b1fc67
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
